# Copyright (c) 2019 The Felicia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

py_binary(
    name = "human_pose_estimation_from_camera",
    srcs = [
        "human_pose_estimation_from_camera.py",
        "openpose.py",
    ],
    main = "human_pose_estimation_from_camera.py",
    deps = ["//external:felicia_py"],
)
