# Copyright (c) 2019 The Felicia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@com_github_chokobole_felicia//bazel:felicia_proto.bzl", "fel_proto_library")

fel_proto_library(
    name = "simple_message_proto",
    srcs = ["simple_message.proto"],
    visibility = ["//:internal"],
)
