# Copyright (c) 2019 The Felicia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

py_binary(
    name = "object_detection_from_camera",
    srcs = [
        "object_detection_from_camera.py",
        "tf_object_detection.py",
    ],
    main = "object_detection_from_camera.py",
    deps = ["//external:felicia_py"],
)
